version: "3"

services:
  consumer:
    build: .
    container_name: kafka_consumer
    depends_on:
      - producer
      - mongodb
    ports: ['5000:5000', '8080:8080', '8081:8081']
    # volumes: ['./:/usr/app']
    # command: ["tail", "-f", "/dev/null"]
    command: ["/bin/bash", "./start_script.sh"]


  producer:
    build: ./producer
    depends_on:
      - mongodb
    container_name: kafka_producer
    # volumes: ['./producer:/usr/app']
    # command: ["tail", "-f", "/dev/null"]

  mongodb:
    image: mongo:latest
    hostname: mongodb_connect
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - 27017:27017

networks:
  default:
    # kafka-network to enable communication between the Kafka cluster and the apps:
    name: kafka-network  
    external: true